env:
  PGHOST: 127.0.0.1
  PGUSER: postgres

name: Submission
on: pull_request
jobs: 
  one:
    name: Update Challenge Status
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Postgresql
        run: sudo apt-get -yqq install libpq-dev
      - name: install-dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --check-files
      - name: CreateDatabase
        run: |
          RAILS_ENV=test
          bundler exec rails db:create
          bundler exec rails db:migrate
      - id: rspec-tests
        continue-on-error: true
        run: bin/rspec
      - name: Tests Failed
        if: steps.rspec-tests.outcome == 'failure'
        uses: wei/curl@v1 
        with:
          args: '-X PATCH -H ''Authorization: Token ${{ secrets.ACTION_TOKEN }}'' ''${{ secrets.ACTION_URL }}?student=${{ github.actor }}&challenge=${{ github.repository }}&status=attempted'''
      - name: Tests Success
        if: steps.rspec-tests.outcome == 'success'
        uses: wei/curl@v1 
        with:
          args: '-X PATCH -H ''Authorization: Token ${{ secrets.ACTION_TOKEN }}'' ''${{ secrets.ACTION_URL }}?student=${{ github.actor }}&challenge=${{ github.repository }}&status=completed'''
